#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

PROJECT_NAME="${PROJECT_NAME:-medicalgpt}"
PROJECT_ROOT_REMOTE="${PROJECT_ROOT_REMOTE:-/scratch/e1561245/cot_yz/medicalgpt}"

RUNTIME_ROOT="${RUNTIME_ROOT:-${PROJECT_ROOT}/runtime/hopper}"
OUTPUT_ROOT="${OUTPUT_ROOT:-${PROJECT_ROOT}/output/hopper}"
PBS_LOG_ROOT="${PBS_LOG_ROOT:-${OUTPUT_ROOT}/pbs_logs}"
ARTIFACT_ROOT="${ARTIFACT_ROOT:-${PROJECT_ROOT}/artifacts/hopper}"

HOPPER_SFT_DATA_DIR="${HOPPER_SFT_DATA_DIR:-${PROJECT_ROOT}/data/hopper_sft}"
HOPPER_REWARD_DATA_DIR="${HOPPER_REWARD_DATA_DIR:-${PROJECT_ROOT}/data/hopper_reward}"
HOPPER_SFT_TRAIN_DIR="${HOPPER_SFT_TRAIN_DIR:-${HOPPER_SFT_DATA_DIR}}"
HOPPER_SFT_VAL_DIR="${HOPPER_SFT_VAL_DIR:-${HOPPER_SFT_DATA_DIR}}"
HOPPER_REWARD_TRAIN_DIR="${HOPPER_REWARD_TRAIN_DIR:-${HOPPER_REWARD_DATA_DIR}}"
HOPPER_REWARD_VAL_DIR="${HOPPER_REWARD_VAL_DIR:-${HOPPER_REWARD_DATA_DIR}}"

MEDICAL_CLOSED_LOOP_PROFILE="${MEDICAL_CLOSED_LOOP_PROFILE:-formal}"
MEDICAL_CLOSED_LOOP_ROOT="${MEDICAL_CLOSED_LOOP_ROOT:-${PROJECT_ROOT}/data/medical_closed_loop/${MEDICAL_CLOSED_LOOP_PROFILE}}"
MEDICAL_CLOSED_LOOP_EVAL_FILE="${MEDICAL_CLOSED_LOOP_EVAL_FILE:-${MEDICAL_CLOSED_LOOP_ROOT}/eval/medical_eval_cases.jsonl}"
MEDICAL_CLOSED_LOOP_MANUAL_RUBRIC="${MEDICAL_CLOSED_LOOP_MANUAL_RUBRIC:-${MEDICAL_CLOSED_LOOP_ROOT}/eval/manual_review_template.csv}"

DATA_BUILD_INCLUDE_HF_PUBLIC_SOURCES="${DATA_BUILD_INCLUDE_HF_PUBLIC_SOURCES:-1}"
DATA_BUILD_HF_MAX_RECORDS="${DATA_BUILD_HF_MAX_RECORDS:-8000}"
DATA_BUILD_SFT_TARGET="${DATA_BUILD_SFT_TARGET:-6000}"
DATA_BUILD_PREFERENCE_TARGET="${DATA_BUILD_PREFERENCE_TARGET:-3000}"
DATA_BUILD_EVAL_TARGET="${DATA_BUILD_EVAL_TARGET:-400}"
DATA_BUILD_GENERAL_QA_RATIO="${DATA_BUILD_GENERAL_QA_RATIO:-0.2}"
DATA_BUILD_MIN_VALIDATION_SIZE="${DATA_BUILD_MIN_VALIDATION_SIZE:-128}"
DATA_BUILD_MIN_PREFERENCE_VALIDATION_SIZE="${DATA_BUILD_MIN_PREFERENCE_VALIDATION_SIZE:-64}"
DATA_BUILD_LOCAL_SFT_SOURCE="${DATA_BUILD_LOCAL_SFT_SOURCE:-${PROJECT_ROOT}/data/sft/medical_sft_1K_format.jsonl}"

HF_HOME="${HF_HOME:-/scratch/e1561245/hf_cache}"
HUGGINGFACE_HUB_CACHE="${HUGGINGFACE_HUB_CACHE:-${HF_HOME}}"
TRANSFORMERS_CACHE="${TRANSFORMERS_CACHE:-${HF_HOME}}"

APPTAINER_MODULE="${APPTAINER_MODULE:-apptainer/1.3.1}"
CONTAINER_IMAGE_URI="${CONTAINER_IMAGE_URI:-docker://pytorch/pytorch:2.5.1-cuda12.4-cudnn9-runtime}"
IMAGE_SIF="${IMAGE_SIF:-${RUNTIME_ROOT}/pytorch_2.5.1-cuda12.4-cudnn9-runtime.sif}"
VENV_DIR="${VENV_DIR:-${PROJECT_ROOT}/.venv}"

BASE_MODEL="${BASE_MODEL:-Qwen/Qwen3.5-2B}"
if [[ "${MEDICAL_CLOSED_LOOP_PROFILE}" == "formal" ]]; then
  DEFAULT_SFT_MAX_TRAIN_SAMPLES=6000
  DEFAULT_RM_MAX_TRAIN_SAMPLES=3000
  DEFAULT_DPO_MAX_TRAIN_SAMPLES=3000
  DEFAULT_RLOO_MAX_STEPS=80
else
  DEFAULT_SFT_MAX_TRAIN_SAMPLES=1000
  DEFAULT_RM_MAX_TRAIN_SAMPLES=500
  DEFAULT_DPO_MAX_TRAIN_SAMPLES=500
  DEFAULT_RLOO_MAX_STEPS=80
fi

SFT_MAX_TRAIN_SAMPLES="${SFT_MAX_TRAIN_SAMPLES:-${DEFAULT_SFT_MAX_TRAIN_SAMPLES}}"
RM_MAX_TRAIN_SAMPLES="${RM_MAX_TRAIN_SAMPLES:-${DEFAULT_RM_MAX_TRAIN_SAMPLES}}"
DPO_MAX_TRAIN_SAMPLES="${DPO_MAX_TRAIN_SAMPLES:-${DEFAULT_DPO_MAX_TRAIN_SAMPLES}}"
RLOO_MAX_STEPS="${RLOO_MAX_STEPS:-${DEFAULT_RLOO_MAX_STEPS}}"

export PROJECT_ROOT
export PROJECT_NAME
export RUNTIME_ROOT
export OUTPUT_ROOT
export PBS_LOG_ROOT
export ARTIFACT_ROOT
export HOPPER_SFT_DATA_DIR
export HOPPER_REWARD_DATA_DIR
export HOPPER_SFT_TRAIN_DIR
export HOPPER_SFT_VAL_DIR
export HOPPER_REWARD_TRAIN_DIR
export HOPPER_REWARD_VAL_DIR
export MEDICAL_CLOSED_LOOP_PROFILE
export MEDICAL_CLOSED_LOOP_ROOT
export MEDICAL_CLOSED_LOOP_EVAL_FILE
export MEDICAL_CLOSED_LOOP_MANUAL_RUBRIC
export DATA_BUILD_INCLUDE_HF_PUBLIC_SOURCES
export DATA_BUILD_HF_MAX_RECORDS
export DATA_BUILD_SFT_TARGET
export DATA_BUILD_PREFERENCE_TARGET
export DATA_BUILD_EVAL_TARGET
export DATA_BUILD_GENERAL_QA_RATIO
export DATA_BUILD_MIN_VALIDATION_SIZE
export DATA_BUILD_MIN_PREFERENCE_VALIDATION_SIZE
export DATA_BUILD_LOCAL_SFT_SOURCE
export HF_HOME
export HUGGINGFACE_HUB_CACHE
export TRANSFORMERS_CACHE
export APPTAINER_MODULE
export CONTAINER_IMAGE_URI
export IMAGE_SIF
export VENV_DIR
export BASE_MODEL
export SFT_MAX_TRAIN_SAMPLES
export RM_MAX_TRAIN_SAMPLES
export DPO_MAX_TRAIN_SAMPLES
export RLOO_MAX_STEPS

ensure_common_dirs() {
  mkdir -p "${RUNTIME_ROOT}" "${OUTPUT_ROOT}" "${PBS_LOG_ROOT}" "${ARTIFACT_ROOT}"
  mkdir -p "${HOPPER_SFT_DATA_DIR}" "${HOPPER_REWARD_DATA_DIR}"
  mkdir -p "${MEDICAL_CLOSED_LOOP_ROOT}"
}

normalize_cuda_visible_devices() {
  if [[ "${CUDA_VISIBLE_DEVICES:-}" == GPU-* ]]; then
    IFS=',' read -ra dev_arr <<< "${CUDA_VISIBLE_DEVICES}"
    last_idx=$(( ${#dev_arr[@]} - 1 ))
    export CUDA_VISIBLE_DEVICES
    CUDA_VISIBLE_DEVICES="$(seq -s, 0 "${last_idx}")"
  fi
}

apptainer_bind_paths() {
  printf "%s" "${PROJECT_ROOT}:${PROJECT_ROOT},/scratch/e1561245:/scratch/e1561245"
}

container_env_exports() {
  cat <<EOF
export HF_HOME="${HF_HOME}"
export HUGGINGFACE_HUB_CACHE="${HUGGINGFACE_HUB_CACHE}"
export TRANSFORMERS_CACHE="${TRANSFORMERS_CACHE}"
export PYTHONPATH="${PROJECT_ROOT}:\${PYTHONPATH:-}"
EOF
}
